### ISSUE TITLE
Rewrite StudentRequests to Kotlin

### ISSUE THREAD

**Issue by NN171** [ImmortalIdiot/RUTLead-Android#6]

**Comment by ImmortalIdiot** [comment]
@Xandr070, on my opinion, the background of the snackbar hurts the eyes. Help me choose a color for it.

![Image](https://github.com/ImmortalIdiot/RUTLead-project-activity/assets/127626768/3571a837-ac81-43fa-8694-e1042b69f4bc)

**Comment by Xandr070** [comment]
> @Xandr070, on my opinion, the background of the snackbar hurts the eyes. Help me choose a color for it.
> 
> ![Image](https://private-user-images.githubusercontent.com/127626768/307343822-3571a837-ac81-43fa-8694-e1042b69f4bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MDMwMDksIm5iZiI6MTcwODcwMjcwOSwicGF0aCI6Ii8xMjc2MjY3NjgvMzA3MzQzODIyLTM1NzFhODM3LWFjODEtNDNmYS04Njk0LWUxMDQyYjY5ZjRiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxNTM4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmNlOThlNDI3MzA5YWFkYzIzNDkyY2U0NGFjYWI4OGViOGVlMWNmYmVkYzA5Mjc4MTE5ODgxYzgyNzg2YTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wh7HCoRXTdn2DuVcVn_JT77aiDA77vIFnZAKD7HHU98)

try to use FF5454. I posted a template in figma

**Comment by Xandr070** [comment]
![image](https://github.com/ImmortalIdiot/RUTLead-project-activity/assets/129608390/c1792c65-813f-4c58-82db-85f659c42899)
![image](https://github.com/ImmortalIdiot/RUTLead-project-activity/assets/129608390/69c01a85-5ee1-4a55-86db-580ca6938d9a)
The same color in settings
